"""
Knowledge Base for Veridian Corp IT Support Agent.
Contains all KB articles (KB-01 to KB-10) and the Asset Management Policy.
"""

KB_ARTICLES = {
    "KB-01": {
        "id": "KB-01",
        "title": "Password Reset",
        "category": "account_access",
        "keywords": ["password", "reset", "locked", "locked out", "login", "account", "unlock"],
        "content": "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required.",
        "resolution_type": "self_service_or_it_direct",
        "requires_approval": False
    },
    "KB-02": {
        "id": "KB-02",
        "title": "VPN Access",
        "category": "network_access",
        "keywords": ["vpn", "remote", "access", "credential", "expired", "contractor", "renew"],
        "content": "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee.",
        "resolution_type": "conditional",
        "requires_approval": "contractors_only"
    },
    "KB-03": {
        "id": "KB-03",
        "title": "Laptop Replacement",
        "category": "hardware",
        "keywords": ["laptop", "replacement", "hardware", "broken", "dead", "not working", "screen", "damage"],
        "content": "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement.",
        "resolution_type": "approval_required",
        "requires_approval": True
    },
    "KB-04": {
        "id": "KB-04",
        "title": "Software Installation Requests",
        "category": "software",
        "keywords": ["software", "install", "application", "app", "catalog", "non-catalog", "browser", "extension", "tool"],
        "content": "Standard software (listed in the approved catalog) can be self-installed. Non-catalog software requires IT Security review, which takes 3-5 business days.",
        "resolution_type": "conditional",
        "requires_approval": "non_catalog_only"
    },
    "KB-05": {
        "id": "KB-05",
        "title": "Printer Troubleshooting",
        "category": "hardware",
        "keywords": ["printer", "print", "paper", "jam", "spooler", "queue", "printing"],
        "content": "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag.",
        "resolution_type": "self_service_or_it_direct",
        "requires_approval": False
    },
    "KB-06": {
        "id": "KB-06",
        "title": "Email Mailbox Quota",
        "category": "email",
        "keywords": ["email", "mailbox", "quota", "full", "storage", "archive", "send", "receive"],
        "content": "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB.",
        "resolution_type": "conditional",
        "requires_approval": "quota_increase_only"
    },
    "KB-07": {
        "id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "category": "network_access",
        "keywords": ["wifi", "wi-fi", "guest", "wireless", "visitor", "internet"],
        "content": "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required.",
        "resolution_type": "self_service",
        "requires_approval": False
    },
    "KB-08": {
        "id": "KB-08",
        "title": "Expense Software Access",
        "category": "software",
        "keywords": ["expense", "finance", "reimbursement", "expense tool", "expense management"],
        "content": "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists.",
        "resolution_type": "redirect",
        "requires_approval": False
    },
    "KB-09": {
        "id": "KB-09",
        "title": "Security Incident Reporting",
        "category": "security",
        "keywords": ["phishing", "malware", "security", "breach", "suspicious", "hack", "unauthorized", "virus"],
        "content": "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees.",
        "resolution_type": "escalate_immediately",
        "requires_approval": False
    },
    "KB-10": {
        "id": "KB-10",
        "title": "Work-From-Home Equipment",
        "category": "hardware",
        "keywords": ["wfh", "work from home", "remote", "monitor", "chair", "home office", "equipment", "allowance"],
        "content": "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved.",
        "resolution_type": "approval_required",
        "requires_approval": True
    }
}

ASSET_MANAGEMENT_POLICY = {
    "id": "ASSET-POLICY",
    "title": "Asset Management Policy (Extract)",
    "issued_by": "Finance & Assets",
    "last_updated": "Q2 2026",
    "content": "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval.",
    "keywords": ["asset", "hardware", "laptop", "monitor", "refresh", "replacement", "4-year", "cycle"]
}


def search_kb(query: str) -> list:
    """Search knowledge base articles by keyword matching."""
    query_lower = query.lower()
    results = []
    
    for article_id, article in KB_ARTICLES.items():
        score = 0
        for keyword in article["keywords"]:
            if keyword in query_lower:
                score += 1
        if any(word in query_lower for word in article["title"].lower().split()):
            score += 1
        if score > 0:
            results.append((score, article))
    
    # Check asset policy too
    asset_score = 0
    for keyword in ASSET_MANAGEMENT_POLICY["keywords"]:
        if keyword in query_lower:
            asset_score += 1
    if asset_score > 0:
        results.append((asset_score, ASSET_MANAGEMENT_POLICY))
    
    results.sort(key=lambda x: x[0], reverse=True)
    return [r[1] for r in results]


def get_kb_article(article_id: str) -> dict | None:
    """Get a specific KB article by ID."""
    if article_id in KB_ARTICLES:
        return KB_ARTICLES[article_id]
    if article_id == "ASSET-POLICY":
        return ASSET_MANAGEMENT_POLICY
    return None


def get_all_articles() -> list:
    """Return all KB articles including the asset policy."""
    articles = list(KB_ARTICLES.values())
    articles.append(ASSET_MANAGEMENT_POLICY)
    return articles


def format_kb_for_context(articles: list) -> str:
    """Format KB articles for inclusion in LLM context."""
    if not articles:
        return "No relevant knowledge base articles found."
    
    formatted = []
    for article in articles:
        formatted.append(
            f"{article['id']}: {article['title']}\n"
            f"   {article['content']}"
        )
    return "\n\n".join(formatted)
